# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(683, 530)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        Form.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 10, 658, 501))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Data = QtWidgets.QTableWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Data.setFont(font)
        self.Data.setObjectName("Data")
        self.Data.setColumnCount(0)
        self.Data.setRowCount(0)
        self.verticalLayout.addWidget(self.Data)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Pre_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Pre_btn.setObjectName("Pre_btn")
        self.horizontalLayout.addWidget(self.Pre_btn)
        self.Vis_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Vis_btn.setObjectName("Vis_btn")
        self.horizontalLayout.addWidget(self.Vis_btn)
        self.Edu_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Edu_btn.setObjectName("Edu_btn")
        self.horizontalLayout.addWidget(self.Edu_btn)
        self.Load_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Load_btn.setObjectName("Load_btn")
        self.horizontalLayout.addWidget(self.Load_btn)
        self.Train_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Train_btn.setObjectName("Train_btn")
        self.horizontalLayout.addWidget(self.Train_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "数据界面"))
        self.Pre_btn.setText(_translate("Form", "数据预处理"))
        self.Vis_btn.setText(_translate("Form", "数据可视化"))
        self.Edu_btn.setText(_translate("Form", "加载教学数据"))
        self.Load_btn.setText(_translate("Form", "加载数据"))
        self.Train_btn.setText(_translate("Form", "开始训练"))
