# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\data_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        Form.setFont(font)
        self.Load_btn = QtWidgets.QPushButton(Form)
        self.Load_btn.setGeometry(QtCore.QRect(40, 390, 141, 41))
        self.Load_btn.setObjectName("Load_btn")
        self.Edu_btn = QtWidgets.QPushButton(Form)
        self.Edu_btn.setGeometry(QtCore.QRect(230, 390, 141, 41))
        self.Edu_btn.setObjectName("Edu_btn")
        self.Pre_btn = QtWidgets.QPushButton(Form)
        self.Pre_btn.setGeometry(QtCore.QRect(430, 390, 141, 41))
        self.Pre_btn.setObjectName("Pre_btn")
        self.Data = QtWidgets.QTableWidget(Form)
        self.Data.setGeometry(QtCore.QRect(50, 20, 501, 341))
        self.Data.setObjectName("Data")
        self.Data.setColumnCount(0)
        self.Data.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "数据界面"))
        self.Load_btn.setText(_translate("Form", "加载数据"))
        self.Edu_btn.setText(_translate("Form", "加载教学数据"))
        self.Pre_btn.setText(_translate("Form", "数据可视化"))
