# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remind_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_remind_windows(object):
    def setupUi(self, remind_windows):
        remind_windows.setObjectName("remind_windows")
        remind_windows.resize(627, 430)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        remind_windows.setFont(font)
        self.centralwidget = QtWidgets.QWidget(remind_windows)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 30, 411, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 120, 341, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(450, 100, 109, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        self.Close_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Close_btn.setGeometry(QtCore.QRect(250, 330, 151, 51))
        self.Close_btn.setObjectName("Close_btn")
        remind_windows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(remind_windows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 627, 25))
        self.menubar.setObjectName("menubar")
        remind_windows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(remind_windows)
        self.statusbar.setObjectName("statusbar")
        remind_windows.setStatusBar(self.statusbar)

        self.retranslateUi(remind_windows)
        QtCore.QMetaObject.connectSlotsByName(remind_windows)

    def retranslateUi(self, remind_windows):
        _translate = QtCore.QCoreApplication.translate
        remind_windows.setWindowTitle(_translate("remind_windows", "教学提示"))
        self.label.setText(_translate("remind_windows", "神经网络平台使用教学以及注意事项"))
        self.textBrowser.setHtml(_translate("remind_windows", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\',\'sans-serif\'; font-size:11pt; font-weight:600;\">注意事项</span><span style=\" font-family:\'微软雅黑\',\'sans-serif\'; font-size:11pt;\">：该网络平台只能够用于多分类问题。</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\',\'sans-serif\'; font-size:11pt; font-weight:600;\">神经元设置</span><span style=\" font-size:11pt; font-weight:600;\">：</span><span style=\" font-family:\'微软雅黑\',\'sans-serif\'; font-size:11pt;\">目标变量为分类变量，有几种类别就有几个输出神经元。假设目标变量为</span><span style=\" font-family:\'微软雅黑\',\'sans-serif\'; font-size:11pt; font-weight:600;\">右侧的表格</span><span style=\" font-family:\'微软雅黑\',\'sans-serif\'; font-size:11pt;\">，那么，那么该分类变量一共有三个类别0,1,2，所以神经网络,设置成三个神经元</span><span style=\" font-size:11pt;\"> </span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("remind_windows", "变量类别"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("remind_windows", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("remind_windows", "1"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("remind_windows", "2"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("remind_windows", "0"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("remind_windows", "2"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("remind_windows", "0"))
        self.Close_btn.setText(_translate("remind_windows", "我懂了"))
